export const ADD_FOLDER = "ADD_FOLDER"
export const REMOVE_FOLDER = "REMOVE_FOLDER"
export const RENAME_FOLDER = "RENAME_FOLDER"
export const SELECT_FOLDER = "SELECT_FOLDER"

export const FETCH_FOLDERS_START = "FETCH_FOLDER_START"
export const FETCH_FOLDERS_SUCCESS = "FETCH_FOLDER_SUCCESS"
export const FETCH_FOLDERS_FAIL = "FETCH_FOLDER_FAIL"

export const UPDATE_FOLDERS_START = "UPDATE_FOLDER_START"
export const UPDATE_FOLDERS_SUCCESS = "UPDATE_FOLDER_SUCCESS"
export const UPDATE_FOLDERS_FAIL = "UPDATE_FOLDER_FAIL"

// export const PUSH_FOLDERS_START = "PUSH_FOLDERS_START"
// export const PUSH_FOLDERS_SUCCESS = "PUSH_FOLDERS_SUCCESS"
// export const PUSH_FOLDERS_FAIL = "PUSH_FOLDERS_FAIL"

// export const DELETE_FOLDERS_START = "DELETE_FOLDERS_START"
// export const DELETE_FOLDERS_SUCCESS = "DELETE_FOLDERS_SUCCESS"
// export const DELETE_FOLDERS_FAIL = "DELETE_FOLDERS_FAIL"

export const ADD_NOTE = "ADD_NOTE"
export const MOVE_TO_TRASH_NOTE = "MOVE_TO_TRASH_NOTE"
export const RENAME_NOTE = "RENAME_NOTE"
export const SELECT_NOTE = "SELECT_NOTE"
export const INPUT_TEXT = "INPUT_TEXT"

export const FETCH_NOTES_START = "FETCH_NOTE_START"
export const FETCH_NOTES_SUCCESS = "FETCH_NOTE_SUCCESS"
export const FETCH_NOTES_FAIL = "FETCH_NOTE_FAIL"

export const UPDATE_NOTES_START = "UPDATE_NOTE_START"
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTE_SUCCESS"
export const UPDATE_NOTES_FAIL = "UPDATE_NOTE_FAIL"

// export const PUSH_NOTES_START = "PUSH_NOTES_START"
// export const PUSH_NOTES_SUCCESS = "PUSH_NOTES_SUCCESS"
// export const PUSH_NOTES_FAIL = "PUSH_NOTES_FAIL"

// export const DELETE_NOTES_START = "DELETE_NOTES_START"
// export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS"
// export const DELETE_NOTES_FAIL = "DELETE_NOTES_FAIL"

//export const CHECK_AUTH_STATE = "CHECK_AUTH_STATE"
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
